// 
// main.cpp generated by embedXcode
// from /Applications/Teensyduino.app/Contents/Java/hardware/teensy/avr/cores/teensy
// at 13 Aug 2021 16:32:46
// ----------------------------------
// DO NOT EDIT THIS FILE.
// ----------------------------------
#if defined(EMBEDXCODE)
 
#include <WProgram.h>

//int main(void) __attribute__((noreturn));
int main(void)
{
	_init_Teensyduino_internal_();

	setup();
    
	while (1) {
		loop();
	}
}

 
 
#include "Charger21_2.ino"
 
#endif // EMBEDXCODE
